stages:
  - monitor
  - build  

cache:
  paths:
    - node_modules/

before_script:
  - yarn install
  - echo "All Packages installed!"

monitor:
  stage: monitor
  image: node:14.17.6
  script:
    - yarn run typecheck
    - echo "Types check successfully!"
    - yarn run lint
    - echo "Lint successfully!"
    - yarn run test:ci
    - echo "Test successfully!"
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

build:
  stage: build
  image: node:14.17.6
  variables:
    CI: 'false'
  script:
    - CI=false  
    - yarn run build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 week
    paths:
      - build
