version: "3.7"

services:

  scriptsure-react:
    container_name: development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 30443:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
