/* eslint-disable no-useless-concat */
export enum StatusColors {
  T = 'green-300',
  G = 'purple-300',
  OS = 'teal-300',
  U = 'pink-300',
  S = 'red-300',
  D = 'blue-300',
  P = 'orange-300',
}

export enum ValidateMethodEnum {
  IDME = 1,
  IDENTRUST = 2,
}

export const reasonCodes = {
  AA: 'Patient unknown to the Provider',
  AB: 'Patient never under  Provider care',
  AC: 'Patient no longer under  Provider care',
  AD: 'Patient has requested refill too soon',
  AE: 'Medication never prescribed for the patient',
  AF: 'Patient should contact Provider first',
  AG: 'Fill/Refill not appropriate',
  AL: 'Change not appropriate',
  AM: 'Patient needs appointment',
  AN: 'Prescriber not associated with this practice or location.',
  AO: 'No attempt will be made to obtain Prior Authorization',
  AP: 'Request already responded to by other means (e.g. phone or fax)',
  AQ: 'More Medication History Available',
  AR: 'Unable to cancel prescription; prescription was transferred to another pharmacy',
  AS: 'Qualified provider unavailable to provide this service',
  AT: 'Not accepting new patients',
  AU: 'Unable to accommodate service based parameters',
  AV: 'These parameters do not meet the patients needs',
  AW: 'Based on assessment, patient needs are outside of contractual agreement',
  AX: 'Patient condition no longer applicable',
  AY: 'Patient not available for service',
  AZ: 'Patient declined service',
  BA: 'Qualified provider unavailable to provide this service',
  BB: 'No Information Available',
  BC: 'Not Authorized to Release',
  BD: 'Unable to Send Response in Format Requested',
  BE: 'Medication denied at patient request',
  BF: 'Conscientious objection',
  BG: 'Not the patient-desired pharmacy',
  BH: 'Not In Central Fill inventory List',
  BJ: 'Out of Stock – The dispensing entity does not have sufficient quantity of the requested product to fulfill the order/prescription.',
  BK: `Quantity to Dispense Incorrect for NDC Sent – NDC requested is for an item that must be distributed 
  in the manufacturer’s packaging and the requested quantity is not an even multiple of the manufacturer’s packaging.`,
  BL: 'Rx Received After Established Deadline – The order was not received in time for the requested shipment date.',
  BM: 'Duplicate Order – More than one message for an order was received.',
  BN: 'Fill Locally not filled by Central Fill Facility',
  BO: `NDC Discontinued from Formulary – Do not resend.  The NDC number requested in on the discontinued 
  inventory list and there is not sufficient quantity of the medication requested to fulfill the order.`,
  BP: 'Out of Stock/Manufacturer Back Order – NDC requested is currently on back order from the manufacturer.',
  BQ: 'Discontinued by Manufacturer – NDC requested has been discontinued by the manufacturer.',
  BR: 'Rx Canceled by Central Fill Facility: Automation – Due to automation issues at the Central Fill Facility the Rx must be filled locally.',
  BS: 'Rx Canceled by Central Fill Facility: Site Closure – Due to site closure issues at Central Fill Facility the Rx must be filled locally.',
  BT: 'Drug Recalled by Manufacturer – NDC requested has been recalled by the manufacturer.',
  BU: 'Eligible for Fulfillment from Central Fill Facility',
  BV: 'Pharmacy not enrolled/aligned with Central Fill Facility',
  BW: 'Change to a different medication',
  BX: 'Electronic Prior Authorization not supported. Submit via other methods.',
  BY: 'Other',
  BZ: 'Can’t find PACase ID',
  CA: 'Unable to locate based on insufficient information - identifiers do not match',
  CC: 'Prior Authorization not required for patient/medication',
  CB: 'Request already processed - final determination has been made',
  CD: 'Cannot find matching patient',
  CE: 'Patient not eligible (does not have coverage with the payer) ',
  CF: 'Prior Authorization duplicate/approved',
  CG: ' Prior Authorization duplicate/in process',
  CH: 'Closed by health plan/payer/processor/PBM',
  CJ: 'Closed by Provider',
  CK: 'Closed by Member',
  CL: 'Attachment type (mimetype) not supported',
  CM: 'Prescriber not allowed to submit PA request',
  CN: 'Response content is inconsistent with the question',
  CO: 'The receiver is not the PA processor for this patient',
  CP: 'The receiver is not the PA processor for this patient and medication combination',
  CQ: 'Transfer needs to be discussed - call with information provided',
  CR: 'Prescription(s) cannot be electronically transferred; will be sent via manual transfer',
  CS: 'Prescription not found',
  CT: 'Prescription cannot be transferred out because it was previously transferred',
  CU: 'Prescription cannot be transferred out because it is voided/cancelled/deactivated',
  CV: 'Stop date has been exceeded',
  CW: 'Prescription cannot be transferred out because it has expired',
  CX: 'Prescription cannot be transferred out by law/regulation',
  CY: 'Prior Authorization duplicate/denied',
  CZ: 'Patient had allergy to requested medication',
  DA: 'Medication has been discontinued',
  DB: 'Drug Use Evaluation',
  DC: 'No refills remaining or medication order has expired',
  DD: 'Pharmacy has no intention to stock the medication requested/prescribed',
  DE: 'Prior Authorization has been denied by payer',
  DF: 'Generic Substitution – A modification of the product prescribed to a generic equivalent.',
  DG: 'Therapeutic Interchange/Substitution – A modification of the product prescribed to a preferred product choice.',
  DH: 'Profile Medication – medication appropriate for administration, not dispensed by pharmacy at this time.',
  DJ: 'No Data – There is a response indicating that no data was found for the search criteria provided in the search request.',
  DK: 'Prescription Data',
  DL: 'Disallowed – There was a permission problem of some type performing this request against this destination.',
  DM: `Error- This response indicates a processing error in performing this request. (May only be used when a more specific ReasonCode does not apply).`,
  DN: 'Excessive days supply according to REMS restrictions.',
  DO: 'Insufficient days supply according to REMS restrictions.',
  DP: 'Inappropriate days supply for the quantity prescribed according to REMS restrictions.',
  DQ: 'Excessive dosage according to REMS restrictions.',
  DR: 'Insufficient dosage according to REMS restrictions.',
  DS: 'Refills not permitted according to REMS restrictions.',
  DT: 'Quantity limit exceeds maximum according to REMS restrictions.',
  DU: 'Inappropriate quantity prescribed according to REMS restrictions.',
  DV: 'Laboratory test results not documented',
  DW: 'Laboratory test not conducted within specified time period.',
  DX: 'Prescribing not authorized due to laboratory test results.',
  DY: 'Prescriber has not documented safe use conditions.',
  DZ: 'Prescriber has not documented patient opioid tolerance.',
  EA: 'Prescriber has not documented that patient has met contraceptive requirements.',
  EB: 'Invalid prescription may not be electronically submitted; hand written orders only.',
  EC: 'Non matched Diagnosis code submitted.',
  ED: 'Patient First Name must be submitted.',
  EE: 'Patient Last Name must  be submitted.',
  EF: 'Patient Zip Code must be submitted.',
  EG: 'Multiple patient matches; call REMS Administrator.',
  EH: 'Patient First Name must be submitted.',
  EI: 'Patient is younger than the minimum age required.',
  EJ: 'Patient is older than the maximum age allowed.',
  EK: 'Patient is on a "Do Not Rechallenge List".',
  EL: 'Patient has not documented safe use conditions.',
  EM: 'Patient must enroll/certify.',
  EN: 'Patient must re-enroll/re-certify.',
  EO: 'Pharmacy not enrolled/certified.',
  EP: 'Pharmacy must re-enroll/re-certify.',
  EQ: 'Pharmacy not matched.',
  ER: 'Invalid Pharmacy type - contact program administrator.',
  ES: 'Presciber must enroll/certify.',
  ET: 'Presciber must re-enroll/re-certify.',
  EU: 'Prescriber qualifications for REMS not met.',
  EV: 'Missing/Invalid Prescriber ID.',
  EW: 'Non-Matched Prescriber last name.',
  EX: 'Prescriber has been deactivated.',
  EY: 'Pharmacy is not participating.',
  EZ: 'Prescriber-Patient Agreement not found.',
  FA: 'No attempt will be made to obtain REMS approval.',
  FB: 'Electronic REMS not supported. Submit via other methods.',
  FC: 'Can not find REMSCaseID',
  FD: 'REMS Authorization not required for patient/medication.',
  FE: 'Patient not eligible',
  FF: 'REMS Authorization duplicate/approved',
  FG: 'REMS Authorization duplicate/in process',
  FH: 'REMS Authorization duplicate/denied',
  FI: 'Closed by REMS Administrator',
  FJ: 'The receiver is not the REMS Administrator for this patient',
  FK: 'The receiver is not the REMS Administrator for this patient and medication combination',
  FL: 'Provider responded after deadline to reply.  PA must be reinitiated',
  FM: 'Product not covered by this plan. Prior Authorization not available. (Used when the drug will not be covered even if the provider does a PA)',
  FN: `Prescription within prescribing limits. Prior Authorization not required for PATIENT/MEDICATION. 
  (Used when there are coverage rules in place, but the prescriber is not going outside of them)`,
  FO: `Coverage limits may exist for quantity and/or days supply. Plan will pay up to coverage limit. 
  Prior Authorization not required for PATIENT/MEDICATION. (Used when the plan will only pay up to a certain amount, but not above.)`,
  FP: 'Coverage limits have been exceeded exception not available. Prior Authorization not required for PATIENT/MEDICATION when within coverage limit.',
  FQ: 'Active PA on file.',
  FR: 'Submitted Product Code is not valid.  Please resolve and resubmit.',
  FS: 'The medication prescribed is out of stock and cannot be obtained in a clinically appropriate timeframe.',
  FT: 'The medication presscribed is available for administration from the Automated Dispensing System',
  FV: 'The medication prescribed is available for cycle fill',
  FW: 'Patient requested reduced quantity.',
  FX: 'Prescriber requested/allowed reduced quantity.',
  FY: 'Days’ Supply and/or Quantity are limited by Payer.',
  FZ: 'Regulatory Days Supply Limitation',
  GA: 'Prescriber Authorization – prescriber must confirm their state license status.',
  GB: 'Prescriber Authorization – prescriber must confirm their DEA license status in prescribing state.',
  GC: 'Prescriber Authorization – prescriber must confirm their DEA registration by DEA class.',
  GD: 'Prescriber Authorization – prescriber must confirm their state Controlled Substance Registration license status.',
  GE: 'Prescriber Authorization – prescriber must confirm their registration by state Controlled Substance Registration class.',
  GF: 'Prescriber Authorization – prescriber must confirm their NADEAN license status.',
  GG: 'Prescriber Authorization – prescriber must obtain/validate Type1 NPI.',
  GH: 'Prescriber Authorization – prescriber must enroll/re-enroll with prescription benefit plan.',
  GI: 'Prescriber Authorization – prescriber must confirm prescriptive authority criteria for prescribed medication is met.',
  GJ: 'Prescriber Authorization – prescriber must enroll/re-enroll in REMS.  ',
  GK: 'Patient unknown to the Provider',
  GL: 'Prescriber Authorization – prescriber must obtain/validate their supervising prescriber.',
  GM: 'Active Registration Status',
  GN: 'In-Active License with prescriptive authority based on state/federal regulations',
  GP: 'Active with Prescriptive Authority – prescribed product class',
  GQ: 'Active with Prescriptive Authority – Prescriber Type',
  GR: 'Active with Prescriptive Authority – Supervising Prescriber Type',
  GS: 'Registered',
  GT: 'Enrolled/Re-Enrolled',
  GU: 'Assigned',
  GV: 'RequestorRole not authorized to receive PDMP data',
};

export const denialReasonTranslates = {
  '000': 'Message has been received by the pharmacy. 000 - Transaction successful; pending',
  '010': 'Message has been received by the pharmacy. 010 - Successfully accepted by ultimate receiver',
  'AA': 'Patient Unknown to the Prescriber',
  'AB': 'Patient Never Under Prescriber Care',
  'AC': 'Patient No Longer Under Prescriber Care',
  'AD': 'Patient Has Requested Refill Too Soon',
  'AE': 'Medication Never Prescribed For The Patient',
  'AF': 'Patient Should Contact Prescriber First',
  'AG': 'Refill Not Appropriate',
  'AL': 'Change not appropriate',
  'AH': 'Patient has picked up prescription',
  'AJ': 'Patient has picked up partial fill of prescription',
  'AK': 'Patient has not picked up prescription, drug returned to stock',
  'AO': 'No attempt will be made to obtain Prior Authorization.',
  'AP': 'Request already responded to by other means (e.g. phone or fax)',
  'AM': 'Patient Needs Appointment',
  'AN': 'Prescriber Not Associated With This Practice Or Location',
  'ZZ': 'Replace Refill Request with New Prescription',
  'ACTIVITY': 'Activity',
  'ADD_COMMENT': 'Add Comment',
  'ADDRESS': 'Address',
  'ALLOWED': 'Allowed',
  'ALTERNATIVE_MEDICATION': 'Alternative Medication',
  'ALTERNATIVE_MEDICATION_TO_DISPENSE': 'Alternative Medication to Dispense',
  'ALTERNATIVE_NOTE': `The pharmacy is unable to fill the Original Prescription. 
  Please click an appropriate substitution from the list below. If there is no equivalent substitution then click Cancel, and Decline the change request.`,
  'APPROVE': 'Approve',
  'APPROVE_SEND': 'Approve And Send',
  'APPROVED': 'Approved',
  'APPROVED_WITH_CHANGES': 'Approved',
  'BEEPER': 'Beeper',
  'BIN': 'BIN #',
  'BIRTH': 'Date of Birth',
  'CANCEL': 'Cancel',
  'CANCEL_CONFIRM': 'Are you sure you want to send a cancel prescription request for {{drugName}} to the pharmacy?',
  'CANCEL_PRESCRIBER': 'You must have a current prescriber selected in order to cancel a prescription.',
  'CANCEL_PRESCRIPTION': 'Cancel Prescription',
  'CANCEL_PRESCRIPTION_STATEMENT': 'Would you like to send a cancel prescription request for the original new prescription that was sent to pharmacy?',
  'CHANGE': 'Change',
  'CHANGE_MEDICATION': 'Change',
  'CHANGE_REQUEST': 'Change Request',
  'CHANGE_RESPONSE': 'Change Response',
  'CHANGE_RXFILL_NOTIFICATIONS': 'CHANGE RXFILL NOTIFICATIONS',
  'CARD_HOLDER': 'Card Holder #',
  'CARDHOLDER_FIRSTNAME': 'Card Holder First Name',
  'CARDHOLDER_LASTNAME': 'Card Holder Last Name',
  'CHART_ID': 'Chart ID',
  'CLEAR_ALL_REFILLS': 'Clear All Refills',
  'CLEAR_ALL_REFILLS_STATEMENT': 'Pending Refills have been removed',
  'CLEAR_ALL_ERRORS_STATEMENT': 'Pending Errors have been removed',
  'CLEAR_SEARCH': 'Clear Search',
  'CLOSE': 'Close',
  'CLOSE_DETAIL': 'Close Detail',
  'COLLAPSE': 'Collapse',
  'COLLAPSE_ALL': 'Collapse All',
  'COMMUNICATION': 'Phone',
  'COMPLETED_PA': 'Complete',
  'COMPLETED_PA_REMOVE': 'Remove PA from pending list',
  'COMPLETED_SUCCESSFULLY': 'The process completed successfully',
  'COMPOUND': 'Compound',
  'CONFIRMATION': 'Confirmation',
  'CONTACT': 'Contact',
  'CONTROLLED_STATEMENT': `By completing the two-factor authentication protocol at this time, you are legally signing the prescription(s) 
  and authorizing the transmission of the above information to the pharmacy for dispensing. 
  The two-factor authentication protocol may only be completed by the practitioner whose name and DEA registration number appear above. 
  You attest that you have used a token separate from the device you are prescribing on 
  (i.e. hard token is separate from the device prescribed on or the code generator or push notification 
    utilized for two-factor authentication  is from another device). Ref. 21 CFR 1311.115.`,
  'CREATE_NEW_MANUAL_PA': 'Create new manual PA',
  'CREATE_PA': 'Create PA',
  'CURRENT_PRACTICE': 'Current practice and prescriber auto selected',
  'DAYS': 'Days',
  'DAYS_SUPPLY': 'Days Supply',
  'DEA': 'DEA',
  'DECIMAL': 'Remove Decimal',
  'DECLINE': 'Decline',
  'DECLINE_PRESCRIPTION': 'Decline Prescription',
  'DECLINED': 'Declined',
  'DECLINED_NEW_PRESCRIPTION_TO_FOLLOW': 'Replace Refill Request with New Prescription',
  'DECLINE_PRESCRIPTION_INHOUSE': 'Are you sure you want to decline the prescription?',
  'DELETE': 'Delete',
  'DELETE_PRESCRIPTION': 'Delete Prescription',
  'DENIAL_REASON': 'Denial Reason',
  'DENIED': 'Denied',
  'DETAILS': 'Details',
  'DETOX': 'Detox',
  'DIAGNOSIS': 'Diagnosis',
  'DIRECTIONS': 'Directions',
  'DIRECTADDRESS': 'Direct Address',
  'DISPENSED_TO_PATIENT': 'Dispensed to Patient',
  'DO_NOT_EXPIRE': 'Do Not Expire',
  'DRUGNAME': 'Drug Name',
  'DURATION': 'Duration',
  'DRU': 'Drug Utilization Review',
  'DRUG_USE_EVALUATION': 'Drug Use Evaluation',
  'EDIT': 'Edit',
  'EDIT_PRESCRIPTION': 'Edit Prescription',
  'ELIGIBILITY_ID': 'Eligibility #',
  'END_DATE': 'End Date',
  'EFFECTIVE_DATE': 'Effective Date',
  'ELECTRONICMAIL': 'EMail',
  'EPCS_II': 'EPCS: Schedule II',
  'EPCS_III': 'EPCS: Schedule III',
  'EPCS_IV': 'EPCS: Schedule IV',
  'EPCS_V': 'EPCS: Schedule V',
  'EPCS_MULTIPLE': 'EPCS: Multiple DEA Class Codes',
  'ERROR': 'Error',
  'ERROR_LENGTH_MAX_2': 'Max length 2',
  'ERROR_LENGTH_MAX_3': 'Max length 3',
  'ERROR_LENGTH_MAX_10': 'Max Length 10',
  'ERROR_LENGTH_MAX_140': 'Max Length 140',
  'EXPAND': 'Expand',
  'EXPAND_ALL': 'Expand All',
  'EXPORT': 'EXPORT',
  'FAX': 'Fax',
  'FEMALE': 'Female',
  'FILLED': 'Fill',
  'FILLED_MARK': 'Mark prescription as Filled',
  'FIND': 'Find New Medication...',
  'FIRST_NAME': 'First Name',
  'FOLLOWUP_1': '1st Followup Request',
  'FOLLOWUP_2': '2nd Followup Request',
  'FOLLOWUP_3': '3rd Followup Request',
  'FOLLOWUP_4': '4th Followup Request',
  'FOLLOWUP_5': '5th Followup Request',
  'GENDER': 'Gender',
  'GENERIC_SUBSTITUTION': 'Generic Substitution',
  'GROUP': 'Group #',
  'GROUPNAME': 'Group Name',
  'HISTORY': 'History',
  'HOW_MANY_REFILL': 'How Many Refills Do You Want To Approve?',
  'HOMETELEPHONE': 'Home',
  'IDENTIFICATION': 'Identification',
  'INGREDIENT_LIST': 'Ingredient List',
  'INHOUSE_APPROVED': 'In-House prescription filled successfully',
  'INHOUSE_DECLINED': 'In-House prescription declined successfully',
  'INHOUSE_PHARMACY': 'In-House Pharmacy',
  'INVALID': 'Invalid entry',
  'INTERNAL': 'Internal',
  'IS': 'is',
  'LAST': 'Last',
  'LAST_FILL_DATE': 'Last Fill Date',
  'LAST_NAME': 'Last Name',
  'LOAD_MORE': 'Load More',
  'MALE': 'Male',
  'MANAGE_PA': 'Manage PA',
  'MANAGE_PA_IN_SMARTAPP': 'Manage PA in Smart Application',
  'MAX_LENGTH_OF': 'Max Length of ',
  'MAXIMUM': 'Maximum',
  'MEDICATION_HISTORY': 'Open Medication History',
  'MESSAGE': 'Messages',
  'MESSAGE_DATE': 'Message Date',
  'MESSAGE_DETAIL': 'Message Detail',
  'MESSAGE_ID': 'Message',
  'MESSAGES_FOUND': 'Messages Found',
  'MINIMUM': 'Minimum',
  'MODIFY_DECISION': 'Modify decision for the message',
  'MODIFY_COMMENT': 'Modify Comment',
  'NDC': 'NDC',
  'NEW': 'New',
  'NEW_PRESCRIPTION': 'New Prescription',
  'NEWRX_STATEMENT': 'Please find and click the medication you would like to send in place of {{medication}}',
  'NO': 'NO',
  'NO_PATIENT': 'Patient must be attached to the message before it can be approved. ' + 'Click green icon  next to patient name to attach patient to message.',
  'NO_STATUS_REPORTED': 'No Status Reported',
  'NOT_ALLOWED': 'Not Allowed',
  'NOTE': 'Note',
  'NOTE_TO_PHARMACIST': 'Pharmacy Note',
  'NPI': 'NPI',
  'NUMBER_OF_REFILLS_REQUESTED': 'Number of Refills Requested',
  'OK': 'OK',
  'OPEN': 'Open',
  'OPEN_CHART': 'Open Chart',
  'ORIGINAL_PRESCRIBER': 'Follow-Up Prescriber',
  'ORIGINAL_PRESCRIPTION': 'Original Prescription',
  'OTHER': 'Other',
  'OTHER_SUGGESTED_ALTERNATIVE': 'Other Suggested Alternative',
  'OTHERTELEPHONE': 'Other',
  'OUT_OF_STOCK': 'Out of Stock',
  'PATIENT': 'PATIENT',
  'PATIENT_LBL': 'Patient',
  'PATIENT_ADD': 'Add new patient',
  'PATIENT_FIND': 'Find existing patient',
  'PATIENT_SEARCH': 'Search for patient...',
  'PATIENT_UPDATED': 'Patient has been updated',
  'PAYERID': 'Payer #',
  'PAYER_TYPE': 'Payer Type',
  'PAYER_TYPE_M': 'Coupon',
  'PAYER_TYPE_L': 'Discount Program',
  'PAYER_TYPE_G': 'Hospice Responsible',
  'PAYER_TYPE_F': 'Managed Care',
  'PAYER_TYPE_E': 'Medicaid',
  'PAYER_TYPE_A': 'Medicare Part A',
  'PAYER_TYPE_B': 'Medicare Part B',
  'PAYER_TYPE_C': 'Medicare Part C',
  'PAYER_TYPE_D': 'Medicare Part D',
  'PAYER_TYPE_P': 'Military / VA',
  'PAYER_TYPE_N': 'Voucher',
  'PAYER_TYPE_K': 'Worker’s Compensation',
  'PAYER_TYPE_ZZ': 'Unknown',
  'PBMMEMBERID': 'PBM Member #',
  'PCN': 'PCN #',
  'PENDING': 'Pending',
  'PRACTICE': 'Practice',
  'PHARMACY_CONTROLLED': 'Pharmacy is unable to receive controlled substances',
  'PHARMACY_DRUG_USE_EVALUATION':
    'Pharmacy has modified the directions for the prescription. ' + 'Please confirm that the medication is clinically valid and click SEND.',
  'PHARMACY_GENERIC_SUBSTITUTION': 'Pharmacist would like to substitute the prescribed medication with a generic equivalent',
  'PHARMACY_NOTE': 'Pharmacy Note',
  'PHARMACY_NOTE_MAX_LENGTH': 'Pharmacy note must be less than 70 characters',
  'PHARMACY_OUT_OF_STOCK':
    'Pharmacy is out of stock of the prescribed medication.' + ' Please select an alternative from below, or close the dialog and send a decline.',
  'PHARMACY_PRIOR_AUTHORIZATION':
    'Pharmacy is requesting that you supply a prior authorization number for the prescription.' +
    ' If the number has not been provided but the medication has been approved,' +
    ' then leave the prior authorization number blank and click send: ',
  'PHARMACY_PRESCRIBER_AUTHORIZATION':
    'The pharmacy is requesting that the following state/federal identification' +
    ' for the prescriber be validated before dispensing. Enter the identification and click SEND: {{messagerequest}}',
  'PHARMACY_REPLACE':
    'Pharmacy is unable to receive a replace type message for controlled substances.' + ' Please deny the message, then prescribe a new prescription.',
  'PHARMACY_SCRIPT_CLARIFICATION':
    'Pharmacy needs some clarification on the prescription.' + ' Please confirm that that the medication is clinically valid and click SEND.',
  'PHARMACY_SERVICE_LEVEL': 'Pharmacy is unable to receive the message type',
  'PHARMACY_SUGGESTED_ALTERNATIVE': 'Pharmacy Suggested Alternative',
  'POPUP_BLOCKER': 'Please Turn off popup blocker on address bar for scriptsure.com',
  'PRESCRIBER': 'Prescriber',
  'PRESCRIBER_AGENT': 'Prescriber Agent',
  'PRESCRIBER_AUTHORIZATION': 'Prescriber Authorization',
  'PRESCRIBER_IDENTIFICATION': 'Prescriber Identification',
  'PRESCRIPTION': 'Prescription Detail',
  'PRESCRIPTION_CANCELLED': ' - Prescription Cancelled',
  'PRIMARYTELEPHONE': 'Phone',
  'PRIOR_AUTHORIZATION': 'Prior Authorization',
  'P2': 'Pharmacy',
  'PY': 'Payer',
  'QUANTITY': 'Quantity',
  'REASON': 'Reason',
  'REFERENCE_NUMBER': 'Reference Number: ',
  'REFILL': 'Refill',
  'REFILL_REMAINING': 'Refill Remaining',
  'REFILL_CLASS': 'Controlled substances sent electronically cannot have refills greater than 5',
  'REFILL_CLASS_II': 'Class-II controlled substances sent electronically refills cannot be greater than 1',
  'REFILL_DECIMAL': 'Refill may not contain a decimal place',
  'REFILL_MAX_LENGTH': 'Refill max length is 2 digits',
  'REFILL_REQUEST': 'Refill Request',
  'REFILL_RESPONSE': 'Refill Response',
  'REFILLS_APPROVED': 'Refills Approved',
  'REMOVE_ORIGINAL': 'Would you like to remove the original prescription from the patient`s chart?',
  'REQUESTED_REFILL': 'Requested Refill',
  'REQUESTED_MEDICATION': 'Requested Medication',
  'RESPONSE_NOTE': 'Response Note',
  'RXFILL': 'RxFill',
  'RXFILL_PRINTED': 'Original Prescription May Have Been Printed or Faxed',
  'REPLACE': 'Replace',
  'REPLACE_PRESCRIPTION': 'Replace Prescription',
  'REPLACE_PRESCRIPTION_CONTROLLED':
    'Replace renewal response is only permissible for controlled substance renewals.' + ' Please select another denial reason.',
  'REPRESCRIBE': 'REPRESCRIBE',
  'RESPONSE': 'Response',
  'REVIEWED': 'Reviewed',
  'REVIEWED_MESSAGE_STATEMENT': 'Message has been reviewed and ready for approval',
  'REVIEWED_BY': 'Reviewed By',
  'REVIEWED_ALL_ERRORS': 'Reviewed All Errors',
  'REQUIRED': 'Required',
  'RXFILL_FILLED': 'Patient has picked up prescription',
  'RXFILL_NOT_FILLED': 'Patient has not picked up prescription, drug returned to stock',
  'RXFILL_PARTIAL_FILLED': 'Patient has picked up partial fill of prescription',
  'RXFILL_TRANSFERRED': 'Prescription has been transferred to another pharmacy',
  'RXFILL_WARNING_PARTIAL': 'Warning only a {{portion}}% of the original prescription was dispensed',
  'RXFILL_INDICATOR': 'Change RxFill Notifications',
  'RXFILL_INDICATOR_NOTIFY': 'RxFill change notification has been sent',
  'RXFILL_INDICATOR_RESULT': 'RxFill notifications have been changed to: ',
  'RXFILL_INDICATOR_STATEMENT': 'Are you sure you want to change notifications for the prescription to {{rxfillIndicatorChange}}',
  'RXFILL_INDICATOR_ALL_FILL_STATUSES': 'All Fill Statuses',
  'RXFILL_INDICATOR_ALL_FILL_STATUSES_EXCEPT_TRANSFERRED': 'All Fill Statuses Except Transferred',
  'RXFILL_INDICATOR_DISPENSED_AND_PARTIALLY_DISPENSED': 'Dispensed And Partially Dispensed',
  'RXFILL_INDICATOR_PARTIALLY_DISPENSED_AND_NOT_DISPENSED': 'Partially Dispensed And Not Dispensed',
  'RXFILL_INDICATOR_NOT_DISPENSED_AND_TRANSFERRED': 'Not Dispensed And Transferred',
  'RXFILL_INDICATOR_PARTIALLY_DISPENSED': 'Partially Dispensed',
  'RXFILL_INDICATOR_NOT_DISPENSED': 'Not Dispensed',
  'RXFILL_INDICATOR_CANCEL_ALL_FILL_STATUSES': 'Cancel All Fill Statuses',
  'SCRIPT_CLARIFICATION': 'Script Clarification',
  'SEARCH': 'Search',
  'SELECT': 'Select',
  'SELECT_ALTERNATIVE_ABOVE': 'Select Alternative From List Above',
  'SELECTED': 'Selected',
  'SEND': 'Send',
  'SEND_APPROVAL': 'SEND APPROVAL',
  'SEND_CANCEL': 'Send Cancel Prescription to Pharmacy',
  'SEND_DECLINE': 'SEND DECLINE',
  'SERVICE_LEVEL': 'Service Level',
  'SERVICE_LEVEL_CONTROLLED': 'Prescriber is unable to send controlled substances to the pharmacy',
  'SERVICE_LEVEL_NEWRX': 'Prescriber is unable to send new prescriptions to the pharmacy',
  'SHOW_ALL': 'Show All',
  'SHOW_DETAIL': 'Show Detail',
  'SHOW_LESS': 'Show Less',
  'SHOW_MORE': 'Show More',
  'SOURCE': 'Source',
  'START_DATE': 'Start Date',
  'STATE_LICENSE': 'State License',
  'STATE_LICENSE_CONTROLLED': 'State Controlled License',
  'STATUS': 'Status',
  'STATUS_ERROR': 'Pharmacy has sent back an error message',
  'STATUS_PENDING': 'Message has been sent to pharmacy and still is in pending status',
  'STATUS_SUCCESS': 'Message has been received by pharmacy successfully',
  'SUPERVISOR': 'Supervisor',
  'SUBSTITUTION': 'Substitution',
  'TITLE': 'Title',
  'TODAY': 'Today',
  'TRANSFERRED_TO_PHARMACY': 'Transferred to Pharmacy',
  'UNKNOWN': 'Unknown',
  'USER_MENU': 'User Menu',
  'VALIDATION': 'Validation',
  'VALIDATION_STATEMENT': 'Please correct any validation errors, and try again',
  'VALIDATION_DEA_STATEMENT': 'The medication is a controlled substance, and must be approved by the prescribing physician',
  'VERIFY': 'Verify',
  'VIEW_ALL': 'View All',
  'VIEW_DETAIL': 'View Detail',
  'VITALS': 'Vitals',
  'WORKTELEPHONE': 'Work',
  'WRITTEN_DATE': 'Written Date',
  'YES': 'Yes',
};
