import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import DrugsFavoritList from './drugs.favorit.list';

export default {
  title: 'Features/Drug/Drugs Favorit List',
  component: DrugsFavoritList,
  argTypes: {
    noCoupon: { control: false },
  },
  parameters: { docs: { source: { type: 'code' } } },
} as ComponentMeta<typeof DrugsFavoritList>;

const Template: ComponentStory<typeof DrugsFavoritList> = ({ ...args }) => <DrugsFavoritList {...args} />;

export const Default = Template.bind({});
Default.args = {
  noCoupon: 0,
  openDetails: action('openDetails'),
  removeFavorit: action('removeFavorit'),
  favoritDrugs: [
    {
      CoPayLong: '',
      CoPayShort: '',
      DrugGroupDescr: '',
      DrugType: '',
      FontColorUser: null,
      FontNameUser: null,
      FontSizeUser: null,
      FontStyleUser: null,
      FormularyStatus: -1,
      GCN_SEQNO: '69024',
      GenericName: '(d)-limonene flavor',
      MED_NAME_TYPE_CD: '2',
      MED_ROUTED_MED_ID_DESC: '(d)-limonene flavor (bulk)',
      Pharmacology: null,
      ROUTED_MED_ID: 160581,
      ReactionCode: '',
      ReasonAllergy: '',
      ReasonInteraction: '',
      TypeId: '40',
      multipletype: 0,
      offerid: null,
      interaction: {
        ROUTED_MED_ID: 52641,
        DDI_DES: 'SELECTED QT PROLONGING AGENTS/ERYTHROMYCIN; TELITHROMYCIN',
        DDI_SL: '2',
      },
      allergy: {
        allergy: 0,
        detail: {
          DAM_AGCCSD: 'SULFONE',
          DAM_AGCSPD: 'SULFONE',
          DAM_ALRGN_GRP: 900237,
          DAM_ALRGN_XSENSE: 264,
          HIC: 'W4PA',
          HIC_SEQN: 3003,
          ROUTED_MED_ID: 6744,
          chemicalDescription: 'dapsone',
          medicationDescription: 'dapsone',
        },
        title: '<b>Ingredient</b>: dapsone',
      },
    },
    {
      CoPayLong: '',
      CoPayShort: '',
      DrugGroupDescr: '',
      DrugType: '',
      FontColorUser: null,
      FontNameUser: null,
      FontSizeUser: null,
      FontStyleUser: null,
      FormularyStatus: -1,
      GCN_SEQNO: '65039',
      GenericName: 'sod Cl irrigat/decyl glucoside',
      MED_NAME_TYPE_CD: '2',
      MED_ROUTED_MED_ID_DESC: '0.9 % sodium chloride-decyl glucoside irrigation',
      Pharmacology: null,
      ROUTED_MED_ID: 152139,
      ReactionCode: '',
      ReasonAllergy: '',
      ReasonInteraction: '',
      TypeId: '2',
      multipletype: 0,
      offerid: null,
      allergy: {
        allergy: 0,
        detail: {
          DAM_AGCCSD: 'SULFONE',
          DAM_AGCSPD: 'SULFONE',
          DAM_ALRGN_GRP: 900237,
          DAM_ALRGN_XSENSE: 264,
          HIC: 'W4PA',
          HIC_SEQN: 3003,
          ROUTED_MED_ID: 6744,
          chemicalDescription: 'dapsone',
          medicationDescription: 'dapsone',
        },
        title: '<b>Ingredient</b>: dapsone',
      },
    },
    {
      CoPayLong: '',
      CoPayShort: '',
      DrugGroupDescr: '',
      DrugType: '',
      FontColorUser: null,
      FontNameUser: null,
      FontSizeUser: null,
      FontStyleUser: null,
      FormularyStatus: -1,
      GCN_SEQNO: '40964,40965',
      GenericName: 'abacavir sulfate',
      MED_NAME_TYPE_CD: '2',
      MED_ROUTED_MED_ID_DESC: 'abacavir oral',
      Pharmacology: 'Abacavir (Brand =)',
      ROUTED_MED_ID: 16830,
      ReactionCode: '',
      ReasonAllergy: '',
      ReasonInteraction: '',
      TypeId: '1',
      multipletype: 0,
      offerid: 2422,
    },
    {
      CoPayLong: '',
      CoPayShort: '',
      DrugGroupDescr: 'OR',
      DrugType: '',
      FontColorUser: '',
      FontNameUser: '',
      FontSizeUser: '',
      FontStyleUser: '',
      FormularyStatus: -1,
      GCN_SEQNO: '',
      GenericName: '',
      MED_NAME_TYPE_CD: '',
      MED_ROUTED_MED_ID_DESC: 'My Order Set',
      Pharmacology: '',
      ROUTED_MED_ID: 29,
      ReactionCode: '',
      ReasonAllergy: '',
      ReasonInteraction: '',
      TypeId: '',
      multipletype: 0,
      offerid: '',
    },
    {
      CoPayLong: '',
      CoPayShort: '',
      DrugGroupDescr: 'CO',
      DrugType: '',
      FontColorUser: '',
      FontNameUser: '',
      FontSizeUser: '',
      FontStyleUser: '',
      FormularyStatus: -1,
      GCN_SEQNO: '',
      GenericName: '',
      MED_NAME_TYPE_CD: '',
      MED_ROUTED_MED_ID_DESC: 'asdf CLONE',
      Pharmacology: '',
      ROUTED_MED_ID: 481,
      ReactionCode: '',
      ReasonAllergy: '',
      ReasonInteraction: '',
      TypeId: '',
      multipletype: 0,
      offerid: '',
    },
  ],
};
